<a href="https://colab.research.google.com/github/Reshmatr2407/Python/blob/python/20_kNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Classification Prblem - for categorising

Logistic Regression( binary 0 and 1)
Sigmoid curve
ln(P/1-P)=a+bX
define Threshold value
confusion matrix

k-NN Algorithm for classification problem
k-Nearest Neighbour Algorithm

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/iris.csv')

df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

all the preprocessing steps are completed..only encoding to be done

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

Perform Label encoding since species is the target column

In [ ]:
lblenc=LabelEncoder()
df['species']=lblenc.fit_transform(df['species'])

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [ ]:
df['species'].unique()

array([0, 1, 2])

ML Model Building

Split target and features

In [ ]:
y=df['species']
x=df.drop('species',axis=1)

In [ ]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: species, dtype: int64

In [ ]:
x.head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

Split for train and test

In [ ]:
# Assuming x and y are defined earlier in your code
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [ ]:
x_train.head()

     sepal_length  sepal_width  petal_length  petal_width
118           7.7          2.6           6.9          2.3
113           5.7          2.5           5.0          2.0
60            5.0          2.0           3.5          1.0
98            5.1          2.5           3.0          1.1
26            5.0          3.4           1.6          0.4

Model creation

Initializing model

In [ ]:

# Initializing the model
knn = KNeighborsClassifier(n_neighbors=3)

# Training the model
knn.fit(x_train, y_train)

# Make prediction using the trained model
y_pred = knn.predict(x_test)  # Change from x_train to x_test for evaluation

In [ ]:
# Evaluation
acc_knn = accuracy_score(y_test, y_pred)
print("Accuracy:", acc_knn)

rec_knn = recall_score(y_test, y_pred, average='weighted')
print("Recall:", rec_knn)

prec_knn = precision_score(y_test, y_pred, average='weighted')
print("Precision:", prec_knn)

Accuracy: 0.9666666666666667
Recall: 0.9666666666666667
Precision: 0.9708333333333333